apiVersion: v1
kind: Service
metadata:
  name: flask-hello-world-service
spec:
  selector:
    app: flask-hello-world
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
