name: Deploy to GKE
env:
  DOCKER_USER: '${{secrets.DOCKERHUB_USERNAME}}'
  DOCKER_TOKEN: '${{secrets.DOCKERHUB_TOKEN}}'
  GCP_SECRET: '${{ secrets.GCP_SECRET }}'
  PROJECT_ID: devops-cbd3375 # TODO: update Google Cloud project id
  GAR_LOCATION: us-central1 # TODO: update Artifact Registry location
  SERVICE: copyninja_1 # TODO: update Cloud Run service name
  REGION: us-central1 # TODO: update Cloud Run service region
  
on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Docker Login
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

          
      - name: Set GCLOUD_PROJECT
        run: echo "GCLOUD_PROJECT=devops-cbd3375" >> $GITHUB_ENV
        
        
      - name: Authenticate with Google Cloud
        run: |
          export GOOGLE_APPLICATION_CREDENTIALS=${{ secrets.GCP_SECRET }}
          gcloud auth activate-service-account devopshub@devops-cbd3375.iam.gserviceaccount.com --key-file=${{ secrets.GCP_SECRET }}
          
      - name: Set up Google Cloud SDK
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@v0.2.0
        with:
          service_account_key: ${{ secrets.GCP_SECRET }}
          project_id: devops-cbd3375
          export_default_credentials: true
      
      - name: Get GKE Credentials
        uses: google-github-actions/get-gke-credentials@main
        with:
          cluster_name: 'simpletest'
          location: 'us-central1'
          
      - name: Update Google Cloud SDK
        run: gcloud components update

      - name: Configure kubectl
        run: gcloud container clusters get-credentials simpletest --region us-central1 --zone us-central1-a --project devops-cbd3375
      
      - name: Build Docker image
        run: |
          docker build -t snehashish97/copyninja_1:${{ github.run_number }} .
          docker images
          docker push snehashish97/copyninja_1:${{ github.run_number }}
          #docker push gcr.io/devops-cbd3375/copyninja_1:${{ github.sha }}
        
      
      - name: Deploy to GKE
        run: |
          kubectl apply -f hello-world-deployment.yaml
          kubectl apply -f hello-world-service.yaml
          
      - name: Show Output
        run: echo ${{ steps.deploy.outputs.url }}
