name: Deploy to GKE
env:
  DOCKER_USER: '${{secrets.DOCKERHUB_USERNAME}}'
  DOCKER_TOKEN: '${{secrets.DOCKERHUB_TOKEN}}'
  GCP_SECRET: '${{ secrets.GCP_SECRET }}'
  
on:
  push:
    branches:
      - main # Change to your branch name if needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Docker Login
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_SECRET }}'
          
      - name: Build Docker image
        run: |
          docker build -t snehashish97/copyninja_1:${{ github.run_number }} .
          docker images
          docker push snehashish97/copyninja_1:${{ github.run_number }}
          docker push gcr.io/devops-cbd3375/copyninja_1:${{ github.sha }}
          
      - name: Configure kubectl
        run: gcloud container clusters get-credentials simpletest --region us-central1 --project devops-cbd3375
        

      - name: Deploy to GKE
        run: |
          kubectl apply -f hello-world-deployment.yaml
          kubectl apply -f hello-world-service.yaml
