name: Deploy to Minikube
env:
  DOCKER_USER: '${{secrets.DOCKERHUB_USERNAME}}'
  DOCKER_TOKEN: '${{secrets.DOCKERHUB_TOKEN}}'
on:
  push:
    branches:
      - main # Change to your branch name if needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Docker Login
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        
      - name: Build Docker image
        run: |
          docker build -t snehashish97/copyninja_1:${{ github.run_number }} .
          docker images
          docker push snehashish97/copyninja_1:${{ github.run_number }}
          
      - name: Start Minikube
        run: minikube start

      - name: Configure kubectl
        run: kubectl config set-context minikube

      - name: Deploy to Minikube
        run: |
          kubectl apply -f hello-world-deployment.yaml
          kubectl apply -f hello-world-service.yaml
          sleep 30

      - name: Verify Deployment
        run: |
          kubectl get pods
          kubectl get service flask-hello-world-service
