name: Deploy to Minikube
env:
  DOCKER_USER: '${{secrets.DOCKERHUB_USERNAME}}'
  DOCKER_PASSWORD: '${{secrets.DOCKERHUB_PASSWORD}}'
on:
  push:
    branches:
      - main # Change to your branch name if needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Build Docker image
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
          docker build -t snehashish97/copyninja_1:${{ github.run_number }} .
          docker images
          docker push snehashish97/copyninja_1:${{ github.run_number }}
          
      - name: Start Minikube
        run: minikube start

      - name: Configure kubectl
        run: kubectl config set-context minikube

      - name: Deploy to Minikube
        run: |
          kubectl apply -f hello-world-deployment.yaml
          kubectl apply -f hello-world-service.yaml
          sleep 30

      - name: Verify Deployment
        run: |
          kubectl get pods
          minikube service flask-hello-world-service
